app/src/Entity/Addresses.php
<?php

namespace App\Entity;

use App\Repository\AddressesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AddressesRepository::class)]
class Addresses
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $address_number = null;

    #[ORM\Column(length: 250)]
    private ?string $street = null;

    #[ORM\Column(length: 250)]
    private ?string $city = null;

    #[ORM\Column(length: 5)]
    private ?string $postal_code = null;

    #[ORM\Column(length: 50)]
    private ?string $country = null;

    #[ORM\Column(length: 50)]
    private ?string $address_type = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $address_supplement = null;

    #[ORM\ManyToOne(inversedBy: 'address')]
     #[ORM\JoinColumn(nullable: false)]
    private ?Users $users = null;

    /**
     * @var Collection<int, Orders>
     */
    #[ORM\OneToMany(targetEntity: Orders::class, mappedBy: 'address')]
    private Collection $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddressNumber(): ?int
    {
        return $this->address_number;
    }

    public function setAddressNumber(int $address_number): static
    {
        $this->address_number = $address_number;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): static
    {
        $this->street = $street;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): static
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getAddressType(): ?string
    {
        return $this->address_type;
    }

    public function setAddressType(string $address_type): static
    {
        $this->address_type = $address_type;

        return $this;
    }

    public function getAddressSupplement(): ?string
    {
        return $this->address_supplement;
    }

    public function setAddressSupplement(?string $address_supplement): static
    {
        $this->address_supplement = $address_supplement;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): static
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return Collection<int, Orders>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setAddress($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): static
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getAddress() === $this) {
                $order->setAddress(null);
            }
        }

        return $this;
    }
}

app/src/Form/AddressesForm.php
<?php

namespace App\Form;

use App\Entity\Addresses;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddressesForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('address_number')
            ->add('street')
            ->add('city')
            ->add('postal_code')
            ->add('country')
            ->add('address_type')
            ->add('address_supplement')

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Addresses::class,
        ]);
    }
}

app/src/Controller/AddressesController.php
<?php

namespace App\Controller;

use App\Entity\Addresses;
use App\Form\AddressesForm;
use App\Repository\AddressesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/addresses')]
final class AddressesController extends AbstractController
{
    #[Route(name: 'app_addresses_index', methods: ['GET'])]
    public function index(AddressesRepository $addressesRepository): Response
    {
        return $this->render('addresses/index.html.twig', [
            'addresses' => $addressesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_addresses_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $address = new Addresses();
        $form = $this->createForm(AddressesForm::class, $address);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $address->setUsers($this->getUser());
            $entityManager->persist($address);
            $entityManager->flush();

            return $this->redirectToRoute('app_addresses_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('addresses/new.html.twig', [
            'address' => $address,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_addresses_show', methods: ['GET'])]
    public function show(Addresses $address): Response
    {
        return $this->render('addresses/show.html.twig', [
            'address' => $address,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_addresses_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Addresses $address, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AddressesForm::class, $address);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_addresses_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('addresses/edit.html.twig', [
            'address' => $address,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_addresses_delete', methods: ['POST'])]
    public function delete(Request $request, Addresses $address, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$address->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($address);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_addresses_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/addresses/_delete_form.html.twig
<form method="post" action="{{ path('app_addresses_delete', {'id': address.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ address.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/addresses/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/addresses/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Addresses{% endblock %}

{% block body %}
    <h1>Edit Addresses</h1>

    {{ include('addresses/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_addresses_index') }}">back to list</a>

    {{ include('addresses/_delete_form.html.twig') }}
{% endblock %}

app/templates/addresses/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Addresses index{% endblock %}

{% block body %}
    <h1>Addresses index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Address_number</th>
                <th>Street</th>
                <th>City</th>
                <th>Postal_code</th>
                <th>Country</th>
                <th>Address_type</th>
                <th>Address_supplement</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for address in addresses %}
            <tr>
                <td>{{ address.id }}</td>
                <td>{{ address.addressNumber }}</td>
                <td>{{ address.street }}</td>
                <td>{{ address.city }}</td>
                <td>{{ address.postalCode }}</td>
                <td>{{ address.country }}</td>
                <td>{{ address.addressType }}</td>
                <td>{{ address.addressSupplement }}</td>
                <td>
                    <a href="{{ path('app_addresses_show', {'id': address.id}) }}">show</a>
                    <a href="{{ path('app_addresses_edit', {'id': address.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_addresses_new') }}">Create new</a>
{% endblock %}

app/templates/addresses/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Addresses{% endblock %}

{% block body %}
    <h1>Create new Addresses</h1>

    {{ include('addresses/_form.html.twig') }}

    <a href="{{ path('app_addresses_index') }}">back to list</a>
{% endblock %}

app/templates/addresses/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Addresses{% endblock %}

{% block body %}
    <h1>Addresses</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ address.id }}</td>
            </tr>
            <tr>
                <th>Address_number</th>
                <td>{{ address.addressNumber }}</td>
            </tr>
            <tr>
                <th>Street</th>
                <td>{{ address.street }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ address.city }}</td>
            </tr>
            <tr>
                <th>Postal_code</th>
                <td>{{ address.postalCode }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ address.country }}</td>
            </tr>
            <tr>
                <th>Address_type</th>
                <td>{{ address.addressType }}</td>
            </tr>
            <tr>
                <th>Address_supplement</th>
                <td>{{ address.addressSupplement }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_addresses_index') }}">back to list</a>

    <a href="{{ path('app_addresses_edit', {'id': address.id}) }}">edit</a>

    {{ include('addresses/_delete_form.html.twig') }}
{% endblock %}