app/src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductsRepository::class)]
class Products
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $product_name = null;

    #[ORM\Column(length: 500)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $price = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $stock = null;


    /**
     * @var Collection<int, Reviews>
     */
    #[ORM\OneToMany(targetEntity: Reviews::class, mappedBy: 'product')]
    private Collection $reviews;

    #[ORM\ManyToOne(inversedBy: 'product')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $categories = null;

    /**
     * @var Collection<int, OrdersProducts>
     */
    #[ORM\OneToMany(targetEntity: OrdersProducts::class, mappedBy: 'products')]
    private Collection $ordersProducts;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->ordersProducts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->product_name;
    }

    public function setProductName(string $product_name): static
    {
        $this->product_name = $product_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }


    /**
     * @return Collection<int, Reviews>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Reviews $review): static
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setProduct($this);
        }

        return $this;
    }

    public function removeReview(Reviews $review): static
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getProduct() === $this) {
                $review->setProduct(null);
            }
        }

        return $this;
    }

    public function getCategories(): ?Categories
    {
        return $this->categories;
    }

    public function setCategories(?Categories $categories): static
    {
        $this->categories = $categories;

        return $this;
    }

    /**
     * @return Collection<int, OrdersProducts>
     */
    public function getOrdersProducts(): Collection
    {
        return $this->ordersProducts;
    }

    public function addOrdersProduct(OrdersProducts $ordersProduct): static
    {
        if (!$this->ordersProducts->contains($ordersProduct)) {
            $this->ordersProducts->add($ordersProduct);
            $ordersProduct->setProducts($this);
        }

        return $this;
    }

    public function removeOrdersProduct(OrdersProducts $ordersProduct): static
    {
        if ($this->ordersProducts->removeElement($ordersProduct)) {
            // set the owning side to null (unless already changed)
            if ($ordersProduct->getProducts() === $this) {
                $ordersProduct->setProducts(null);
            }
        }

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }
}

app/src/Form/ProductsForm.php
<?php

namespace App\Form;

use App\Entity\Categories;
use App\Entity\Products;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class ProductsForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('product_name', options: [
                'label' => 'Nom du produit'
            ])
            ->add('description', options: [
                'label' => 'Description'
            ])
            ->add('price', NumberType::class, [
                'label' => 'Prix (€)',
                'scale' => 2,
            ])
            ->add('stock', IntegerType::class, [
                'label' => 'Stock',
            ])
            ->add('picture', FileType::class, [
                'label' => 'Image du produit',
                'mapped' => false,
                'constraints' => [
                    new Image(
                        mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
                        mimeTypesMessage: 'seuls les formats jpeg, png et webp sont autorisés',
                    )
                ]
            ])
            ->add('categories', EntityType::class, [
                'class' => Categories::class,
                'choice_label' => 'name',
            ])
            ->add('Valider', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Products::class,
        ]);
    }
}

app/src/Controller/ProductsController.php
<?php

namespace App\Controller;

use App\Entity\Products;
use App\Form\ProductsForm;
use App\Repository\ProductsRepository;
use App\Service\PictureService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

final class ProductsController extends AbstractController
{
    #[Route('/produit', name: 'app_products_index', methods: ['GET'])]
    public function index(ProductsRepository $productsRepository): Response
    {
        return $this->render('products/index.html.twig', [
            'products' => $productsRepository->findAll(),
        ]);
    }

    #[Route('/produit/ajouter', name: 'app_products_new', methods: ['GET', 'POST'])]
    public function add(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger, PictureService $pictureService): Response
    {
        $product = new Products();
        $form = $this->createForm(ProductsForm::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $picture = $form->get('picture')->getData();

            if ($picture){
                //Appel du Picture service
                $newName= $pictureService->square($picture,'products', 300);
                //On stock le nom de l'image
                $product->setPicture($newName);
            }


            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('app_products_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('products/add.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/produit/{id}/details', name: 'app_products_show', methods: ['GET'])]
    public function show(Products $product): Response
    {
        return $this->render('products/show.html.twig', [
            'product' => $product,
        ]);
    }

    #[Route('produit/{id}/modifier', name: 'app_products_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Products $product, EntityManagerInterface $entityManager, PictureService $pictureService): Response
    {
        $form = $this->createForm(ProductsForm::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $newPicture = $form->get('picture')->getData();
            if ($newPicture){
                //Appel du Picture service
                $newName= $pictureService->square($newPicture,'products', 300);
                //On stock le nom de l'image
                $product->setPicture($newName);
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_products_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('products/edit.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/produit/{id}/supprimer', name: 'app_products_delete', methods: ['POST'])]
    public function delete(Request $request, Products $product, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $product->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_products_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/products/_delete_form.html.twig
<form method="post" action="{{ path('app_products_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/products/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

app/templates/products/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Products{% endblock %}

{% block body %}
    <h1>Create new Products</h1>

    {{ include('products/_form.html.twig') }}

    <a href="{{ path('app_products_index') }}">back to list</a>
{% endblock %}

app/templates/products/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Products{% endblock %}

{% block body %}
    <h1>Edit Products</h1>

    {{ include('products/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_products_index') }}">back to list</a>

    {{ include('products/_delete_form.html.twig') }}
{% endblock %}

app/templates/products/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/anais.css') }}">
{% endblock %}


{% block title %}Products index{% endblock %}

{% block body %}
    <h1>Nos produits</h1>

    <div class="product-grid">
        {% for product in products %}
            <div class="product-card">
                {% if product.picture %}
                    <img class="product-card" src="{{ asset('uploads/products/' ~ product.picture) }}" alt="{{ product.productName }}">
                {% else %}
                    <div class="no-image">Image non disponible</div>
                {% endif %}

                <h2>{{ product.productName }}</h2>
                <p class="price">{{ product.price | number_format(2, '.', ' ') }} €</p>

                <a href="{{ path('app_products_show', {'id': product.id}) }}" class="btn">Voir plus</a>
            </div>
        {% else %}
            <p>Aucun produit trouvé</p>
        {% endfor %}
    </div>
{% endblock %}

app/templates/products/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Products{% endblock %}

{% block body %}
    <h1>Create new Products</h1>

    {{ include('products/_form.html.twig') }}

    <a href="{{ path('app_products_index') }}">back to list</a>
{% endblock %}

app/templates/products/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ product.productName }}{% endblock %}

{% block body %}
    <div class="">
        <div class="">
            <h1>{{ product.productName }}</h1>
        </div>

        <div class="product">
            {# Image du produit #}
            <div class="product-image">
                {% if product.picture %}
                    <img src="{{ asset('uploads/' ~ product.picture) }}"
                         alt="Image du produit {{ product.productName }}">
                {% else %}
                    <p>Aucune image disponible.</p>
                {% endif %}
            </div>

            <div class="quantity">
                <select class="">
                    <option disabled selected>Quantité</option>
                    {% for i in 1..10 %}
                        <option value="{{ i }}">{{ i }}</option>
                    {% endfor %}
                </select>
            </div>

            {# Prix et bouton panier #}
            <div class="">
                <div class="">{{ product.price|number_format(2, ',', ' ') }}€</div>
                <button class="ajouter-panier"
                        data-id="{{ product.id }}"
                        data-name="{{ product.productName }}"
                        data-description="{{ product.description }}"
                        data-price="{{ product.price }}"
                        data-stock="{{ product.stock }}"
                        type="button">
                    Ajouter au Panier
                </button>
            </div>

            {# Icône de like ou favori #}
            <div class="favory">
                <span>♡</span>
            </div>

            {# Paiement #}
            <div class="icons">
                <svg id="visa" width="50" height="30" xmlns="http://www.w3.org/2000/svg">
                    <use href="{{ asset('images/sprite.svg#visa') }}"></use>
                </svg>
                <svg id="mastercard" width="50" height="30" xmlns="http://www.w3.org/2000/svg">
                    <use href="{{ asset('images/sprite.svg#mastercard') }}"></use>
                </svg>
            </div>
        </div>

        <footer class="footer">
            Copyright© {{ "now"|date("Y") }} – Mentions Légales
        </footer>
    </div>
    <a href="{{ path('app_products_index') }}">back to list</a>

    <a href="{{ path('app_products_edit', {'id': product.id}) }}">edit</a>

    {{ include('products/_delete_form.html.twig') }}
{% endblock %}

